- rustic-lsp.el
- rustic-util.el
> Update lsp mode support

- rustic-cargo.el
> Implement 'cargo new' command

- rustic-util.el
> update call to lsp-rust-switch-server

- rustic-util.el
This saves the position and the markers in the buffer, so there is no need to go to` rustic-save-pos`. This plays better with e.g. grep, as otherwise all grep markers would be destroyed when replacing the contents of the buffer with `copy-to-buffer`.
While `replace-buffer-contents` was added in Emacs 26.1, it was broken for non-ASCII contents and would corrupt the buffer contents. This was fixed in 26.2, so we require version 26.2 for this.
> In emacs >= 26.2, use replace-buffer-contents after formatting

- rustic-compile.el
@tarsius is this something you could do in a hook without issues ?
> compile-hook

- README.md
- rustic-compile.el
> update and document faces

- rustic.el
> add keyword async to rustic-top-item-beg-re

- rustic-util.el
- rustic.el
> rustic-format-buffer: remove format file functionality

- rustic-doc.el
> Silence byte-compiler warnings

- rustic-util.el
close #172
@zw963 @samhedin @thor314 Please test both commands.
> fix rustic-format-buffer position after error

- rustic-cargo.el
> introduce rustic-cargo-run-mode to allow user input

- rustic-util.el
> rustic-rustfix: change function call

- rustic-cargo.el
- test/rustic-cargo-test.el
Fixes #214 by adjusting `rustic-cargo-fn-regexp`
> Fix/rustic cargo-fn-regexp #214

- README.md
Closes https://github.com/brotzeit/rustic/issues/217
> readme: Add section on LSP + TRAMP

- rustic-cargo.el
Adds `rustic-cargo-init`, and refactors both interactive functions to use the same underlying function, since they're almost identical commands.
> Adds rustic-cargo-init

- rustic-common.el
@hniksic does this work for you ?
> Revert "Search for Cargo.lock instead of Cargo.toml"

- rustic-doc/convert.sh
For https://github.com/brotzeit/rustic/issues/248
> Fix line to get macos cpu cores

- rustic-cargo.el
Similar to rustic-cargo-tests.
> Teach rustic-cargo-clippy to take arguments

- rustic-rustfmt.el
- test/rustic-workspace-test.el
> use function to choose correct version of project-root function

- README.md
- rustic-babel.el
> introduce babel keyword :use

- README.md
- rustic-rustfmt.el
- test/rustic-format-test.el
close #326
@yagehu can you give it a try ? 
`(setq rustic-rustfmt-args "+nightly")`
> allow passing additional parameters with rustic-rustfmt-args

- Cask
- rustic.el
instead of removing rust-mode hooks and adding rustic hooks
close #324
> set rust-mode format hook funtions

- README.md
- rustic-popup.el
> introduce option rustic-kill-buffer-and-window

- rustic-doc/filter.lua
I'm getting the below error when trying to use `rustic-doc-setup`. I imagine that there may be an issue with the lua script, but perhaps its something on my side as well. I'm not familiar enough with lua myself, unfortunately.
<details>
<summary>
Error message when running `rustic-doc-setup`
</summary>
```sh
Generating org files in: /home/user/.local/share/emacs/rustic-doc/std
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua:
table expected, got function
while retrieving list
Error running filter /home/user/.local/bin/rustic-doc-filter.lua: …
```
> rustic-doc-setup conversion error

- README.md
- rustic-rustfmt.el
> remote formatting with rustic-format-buffer

- rustic-cargo.el
> use rustic-cargo-bin to call cargo

- README.md
- rustic-flycheck.el
> automatically detect toolchain and use correct clippy params

- rustic-babel.el
- rustic-cargo.el
- rustic-rustfix.el
- rustic-rustfmt.el
- rustic.el
- test/rustic-format-test.el
> introduce additional variable for remote cargo and rustfmt location

- rustic.el
I don't use these bindings, so if somebody knows a better solution...
close #313
> add more commands to rustic-mode-map

- rustic-cargo.el
This improves the plain cargo run functionality:
- Makes cargo run buffer non editable. The original behaviour is
retained when comint is enabled.
- Introduces rustic-run-arguments similar to rustic-test-arguments
- Binds the key 'g' for doing re-run in the cargo run buffer
Note: This functionality needs to be tested by people who use comint
functionality with rustic-mode (Although I don't understand it's
usecase since Rust doesn't have a REPL workflow)
> Improve cargo run functionality when used without comint

- rustic-rustfmt.el
- test/rustic-format-test.el
- test/test-helper.el
> remove rustfmt warnings in buffer and echo them instead

- rustic-cargo.el
Fixes https://github.com/brotzeit/rustic/issues/392
> Fix when executing cargo run from popup

- README.md
- rustic-lsp.el
> don't change eglot-ignored-server-capabilites

- README.md
- rustic-cargo.el
Built on top of the rustic's compilation mode.
> Integrate cargo install with rustic

- rustic.el
> Pass process-environment and exec-path through with-temp-buffer 

- README.md
- rustic-cargo.el
- rustic.el
> Automatically add missing dependencies

- rustic-babel.el
- rustic-comint.el
- rustic-doc.el
> Fix some docstring issues that caused compiler warnings

- README.md
> improve installation section for package.el

- README.md
- rustic-cargo.el
> introduce new option that allows reusing args with cargo commands
