rustic-flycheck.el, rustic-util.el
Fixes #35, #36 (Just added `lsp-workspace-folders-add`), and #21 (Accepting `(and ((not (package-install 'lsp-mode)) (featurep 'lsp-mode)))`).
=> Fix several issues

rustic.el
Keybinding is choosen to mirror cargo.el.
=> Bind rustic-cargo-check to "C-c C-c C-k"

rustic-cargo.el, rustic.el
This new command can be used to run only the test near the point.
It should work for all the cases bellow:
```
fn test_nothing() {
assert!(false);
}
fn test_something() {
assert!(true);
}
mod tests {
#[test]
fn wut_nothing() {
assert!(false);
}
#[test]
fn wut_something() {
assert!(true);
}
}
```
Tests will be added in the following commit.
Closes #43.
=> add rustic-cargo-current-test and bind it to "C-c C-c C-c"

rustic-util.el
Currently it's pointing to `play.rustic-lang` which should presumably be `play.rust-lang`.
=> Fix playground url

README.md, rustic-cargo.el, rustic-util.el
- When running 'cargo new', the newly created project can now be opened
automatically if the user specifies it via the variable
```rustic-cargo-open-new-project```. Its default is set to ```t```
- Add more docstrings for interactive functions which use cargo. A bit redundant
given their name but its still good to have docstrings for all functions.
- Add a convenience command to automatically open the `Cargo.toml` file if the current buffer is visiting a rust project.
=> Add ability to open new project on creation. Add more docstrings

README.md, rustic-compile.el
I'm not sure why this "works", but the cursors position seems to be correct when setting `compilation-scroll-output` to nil/t. But this is far from ideal. Maybe somebody figures out how to integrate compile.el better.
=> Compilation scroll output

rustic.el
rustic defines a rustic-mode-map keymap, not rustic-map. this fix will
properly show the available bindings when running M-x
describe-mode (C-h m) while in rust source buffer.
=> use right keymap name in rustic-mode docstring

rustic-racer.el
racer-rust-src-path doesn't exist, replace it with
rustic-racer-rust-src-path.
=> rustic-racer.el: use right var name in error msgs

.travis.yml, Makefile, rustic-babel.el, rustic-util.el, test/rustic-babel-test.el, test/rustic-rust-mode-test.el, test/test-helper.el
cf melpa/melpa#6462
The elpa key expiration has wrought havoc among elisp repos that actually conduct proper testing, proving once again that no good deed goes unpunished.
=> Expired Elpa Keys

rustic-util.el
This is a simpler way to determine if lsp-mode or eglot is available, without depending on package.el.
`(require X nil t)` returns nil if it fails to load `X`, but will return non-nil if it succeeds.
=> Refactor package.el dependency out of lsp client setup

rustic-util.el
Sorry about that. It seems I had one ) too many in #87, which wasn't correctly fixed in #89, causing `void-function t` errors. This PR fixes that.
=> Fix prematurely terminated cond

rustic-util.el
This acts as a workaround for #85.
It appears lsp-mode has changed the way that loading lsp-clients works, and simply requiring
lsp-clients does not appear to be enough anymore, so we additionally directly require lsp-rust.
=> Manually load lsp-rust

rustic.el, test/rustic-rust-mode-test.el
Thanks @phillord
@brownjohnf can you test this please.
close #107
=> upstream: Re-implement rust-in-macro for performance

rustic.el
rustic-macro-scopes is not correctly cached during
rustic-syntax-propertize, meaning multiple calls are made to
rustic-macro-scope during syntax analysis.
=> Cache macro locations in rustic-syntax-propertize

rustic.el
Thanks to tspiteri
As discussed here https://github.com/brotzeit/rustic/issues/107, this should also speed up syntax-propertize for files with lots of `->` or `=>` symbols in it.
=> upstream: Check for -> and => early in rust-ordinary-lt-gt-p

rustic-cargo.el, rustic-interaction.el
Tweak regex strings a bit. Without this change, no tests are run with `rustic-cargo-current-test`
=> Recognize async functions when running individual tests

README.md, rustic-babel.el, rustic-common.el, rustic-compile.el, rustic-util.el, test/rustic-format-test.el
This PR adds a `defcustom` called `rustic-rustfmt-args` that specifies a list of arguments to `rustfmt`.
This variable is honored by `rustic-format-buffer` and `rustic-format-start-process`.
I have decided to not make `rustic-cargo-fmt` honor this setting, because this function reformats the entire project and should therefore only obey the project-wide `rustfmt.toml`. Fixes #117.
=> Add rustic-rustfmt-config-alist.

rustic.el
Just a suggestion.
Rustic requires rust-mode to be installed, I think. So I have found a little inconsistency in loading (caused by own overly complex set up). Currently, it's not straight-forward to see visually which package is loaded and operational in a buffer.
=> Change Lighter to Rustic

rustic-cargo.el, rustic-compile.el, rustic-popup.el, rustic-racer.el, rustic.el, test/rustic-font-lock-test.el
As mentioned at (info "(emacs)Defining Faces") "[the name of a face]
should not end in "-face" (that would be redundant).  For historic
reasons a few built-in faces actually do end with "-face" and it so
happens that many of our faces are closely related to just those
`font-lock` and `compilation` faces and that probably inspired our
use of the suffix.  Even so, we should stop now.
PS: I did not base this on the latest tip of `master` because there is a recent regression, which I did not wish to investigate.  `make` should tell you about that issue.
=> Remove "-face" suffix from names of faces

rustic-util.el
`rustic-format-file-sentinel` function restore char point when Rustfmt exit on success.
So when first save and rustfmt cause error, char-point move to buffer start.
I fix to restore point process and when rustfmt cause error.
=> fixed: restore char point when rustfmt error

rustic.el
as I mentioned in issue #140,
and this keyword exists in rust-mode.el (L326)
=> add keyword `dyn`

README.md, rustic-doc.el
Also removes the requirement of PCRE2. This changes the search results slightly but apparently, the rg installed with cargo does not have support for it. Hopefully, it's a worthwhile tradeoff.
=> Prompt user to install (some of the) dependencies for rustic doc

README.md
Hi there,
I had an issue with rustic which had been documented, but which I couldn't find! I thought I'd improve the message a little and link to a [bug report I've submitted ](https://github.com/rust-lang/rustfmt/issues/4454)on `rustfmt` to encourage a more intuitive error message.
=> Improve docs for edition = "2018" rustfmt requirement

README.md, rustic-cargo.el
For https://github.com/brotzeit/rustic/issues/150
`missing-imports` is just a list at the moment. What is the preferred way to prompt the user to select one of them? An alternative would be to just add all missing dependencies. I'm not sure how often a user would input several missing dependencies and then only want to add a subset of them. And in those cases, you could just not run `rustic-cargo-add-missing-import`.
=> Add missing dependencies

README.md, rustic-cargo.el
Sorry we have to revert it for now. I just realized that that this will throw an error for eglot users.
=> Revert "rustic-cargo-add-missing-imports (#161)"

rustic-common.el
https://github.com/brotzeit/rustic/issues/174
How about this?
=> Use cargo metadata to find workspace root

rustic-compile.el, rustic-flycheck.el
This tweaks a couple of calls so that rustic works with cargo, etc on a remote machine.  As far as I can tell it doesn't have any effect on a more conventional local setup.
=> Use Tramp aware calls

rustic-flycheck.el
In lsp-mode, json-object-type gets let-bound to 'hash-table prior to
invoking rustic-flycheck-get-cargo-targets:
https://github.com/emacs-lsp/lsp-mode/blob/936dd86142c43e01f38d8b6aaf920b32a8ea2be4/lsp-mode.el#L6809
I noticed this when I opened a Rust file in emacs-tree-sitter. I'm using Emacs 28 native-compiled with rust-analyzer and lsp-mode. lsp-mode was compiled with `lsp-use-plists` set to `t`.
``` emacs-lisp
Error in rustic-flycheck-setup: (wrong-type-argument listp #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data ("packages" (#s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data ("name" "emacs-tree-sitter" "version" "0.12.1" "id" "emacs-tree-sitter 0.12.1 (path+file:///home/brian/.emacs.d/straight/repos/emacs-tree-sitter/core)" …
```
=> Enforce 'alist for json-object-type

Cask, Makefile, rustic-doc.el, rustic.el
`async` is used by `rustic-doc.el`.
Also silence a separate byte-compiler warning.
=> Add async as a dependency

rustic-compile.el
This PR adds (setq next-error-last-buffer buf) e.g. in rustic-compilation as described by @birkenfeld in issue #102.
In my limited testing, this does seems to enable next-error to iterate through errors in the rustic-compilation buffer.
=> fix issue #102 (setq next-error-last-buffer buf) in rustic-compilation.

rustic-cargo.el
This reads arguments for the `cargo run` command from the minibuffer and
saves the history.
I was missing this feature when switching form the default `compile` or
`projectile-run-project`.
=> rustic-cargo-run: minibuffer and history

rustic-compile.el, rustic-doc.el, rustic-util.el, rustic.el
Don't depend on `async` because doing so is completely unnecessary and don't depend on `projectile` because it should not be forced on users for the sake of some minor functionality (which we can also have without using `project` instead).
=> No longer depend on async and projectile

rustic-babel.el, test/rustic-babel-test.el
Allow crate features to be specified with a `:features` header in the babel block
=> iss-210: rustic-babel add crate features

rustic-util.el
Use generic function project-roots to retrieve the roots instead of calling cdr directly
Some setups add a custom function to project-find-functions, so the generic function project-roots should be used instead of directly calling cdr on the result of project-current.
=> Use generic function project-roots to retrieve the roots instead of calling cdr directly

.github/workflows/test.yml, .gitignore, Cask, Makefile, rustic-util.el, rustic.el
I have observed sporadic `Missing dependency: "https://elpa.gnu.org/packages/spinner-1.7.3.el: Bad Request"`.  The added github action caching should hopefully cut down on elpa networking vagaries.
=> Cask ministrations

rustic-cargo.el
This is particularly useful for tests that only run when certain features are enabled.
Also defaulting the minibuffer with `rustic-test-arguments` when an arg is passed to `rustic-cargo-test`
=> Make rustic-cargo-current-test honor rustic-test-arguments

README.md
To fix issue #259, I suppose rust-analyzer's path should be to set to rustic-analyzer-command instead of lsp-rust-analyzer-server-command.
=> Use rustic-analyzer-command

rustic-cargo.el
When learning RUST and making exercises I found that you can provide an `env` variable only then invoking `rustic-cargo-run` with an argument like `C-u`. It also didn't save the command to history. Basically, invoking `rustic-cargo-run` with an argument allows you to run any arbitrary command.
I just added a function to make running an arbitrary command explicitly and have history memorization. It's very helpful to edit the command if there has been a typo. It should also simplify assigning it a key binding.
=> Run any shell command for current project

README.md, rustic-cargo.el
Previously, this function would always pick the previous fn to run,
even when the current point was a module or inside a module. The
function could be from a previous module, which didn't make sense.
Running all tests in a module is a common thing to do.
This change allows users to do that.
If they are within a fn, the fn only is run.
If they are not within a fn but there's a surrounding mod, then the
whole mod is run.
=> Made cargo-run-current-test choose closest of mod or fn to run.

rustic.el
Use rust-top-item-beg-re instead when hitting C-M-a
I found C-M-a not working with `unsafe fn` and figured out `rust-top-item-beg-re` is overridden by `rustic-top-item-beg-re`
=> Remove rustic-top-item-beg-re

README.md, rustic-cargo.el
Attempt at addressing #295, take 2, this time targeting master.  Sorry about the clumsiness; I'm not an engineer, and not very used to collaborating on github.
(Rest of the message is same as before.)
The dependency on polymode is entirely optional; the user needs polymode only if they enable rustic-cargo-run-use-comint. One minor issue is its reliance on an undocumented variable in polymode, but hopefully that's OK as: a) polymode is rather careful to implement this functionality, so I don't think it'll go away in the future; b) the whole thing can be disabled if anything goes wrong.
Technical details:
rustic-cargo-run-mode is renamed to rustic-cargo-plain-run-mode. rustic-cargo-comint-run-mode is added anew. rustic-cargo-run-mode now refers to a wrapper mode that switches between the …
=> Cargo run polymode

README.md, rustic-babel.el, test/rustic-babel-test.el
close #267(Maybe)
related: #266
Auto wrap whole block body in a `fn main` function call if none exists.
Since this is very handy in most code snippets, so the default value is `yes`.
`no` if you don't want this feature(for example, you don't want regex search slow things down).
You can also set a default value by:
``` elisp
;; By setq this default to `nil`, you'll have to explict set params to ":main yes" in each block
(setq rustic-babel-auto-wrap-main nil)
```
```
#+begin_src rust :main yes
let x = vec![1, 2, 3].iter().map(|&x| x + 1).collect::<Vec<_>>();
println!("{:?}", x);
#+end_src
#+results:
: [2, 3, 4]
```
=> rustic-babel: support auto wrap src block body in a `fn main` if none exists

rustic-cargo.el
Cargo run with default argument  within `examples`
close #307
=> rustic-cargo: default `--example` run argument within examples mod

README.md, rustic-babel.el
now that it's possible to have more complex babel projects
with the keywords :include and :use, it can be useful to
inspect the generated project
=> find generated babel project with rustic-babel-visit-project

rustic-babel.el, test/rustic-babel-test.el
```org
#+begin_src :crates '((tokio . "1") (mini-redis . "0.4.1")) :main yes
#[tokio::main]
pub async fn main() -> Result<()> {
Ok(())
}
#+end_src
```
Although `async main` is not official rust syntax, this `tokio::main` is very common. 
Adding this support would be reasonably helpful and comprehensible.
close #317
=> rustic-babel: and support async main for main wrap(#317)

rustic.el
rustic-compile-directory-method expects a function that returns the path to a directory.
Setting `(setq rustic-compile-directory-method 'rustic-buffer-workspace)` seems to have an issue when 
rustic-buffer-workspace returns /root/of/workspace/Cargo.toml.   In this case, rustic-cargo-check fails with the message:
```
apply: Setting current directory: Not a directory, /root/of/workspace/Cargo.toml
```
This patch removes the /Cargo.toml from the path, so that rustic-buffer-workspace returns the parent dir.
=> rustic-buffer-workspace should return the directory instead of Cargo.toml

README.md, rustic-doc.el
* Run `rustic-doc-convert-current-package` after setup.
* Update documentation
* Add optional argument to `rustic-doc-setup` to avoid re-downloading online resources.
=> Rustic doc housekeeping

rustic-lsp.el, rustic-rustfmt.el
Fix macro expanding, remove incorrect nightly check in rustic-format-region, update syntax and idents in rustic-macro-expansion-mode
=> Fix macro expanding, remove incorrect nightly check

rustic-cargo.el
This overrides the keybinding `g` to rustic-cargo-test-run which IMO
is more appropriate than just compiling in the rustic-cargo-test-mode
=> Add rustic-cargo-test-mode-map

rustic-cargo.el
Fixes error caused by duplicate test names being passed to `cargo test`.
Fixes https://github.com/brotzeit/rustic/issues/366.
=> remove duplicate args in rustic-cargo-run-test

rustic-cargo.el
This makes it quite similar to the other functions like build, run commands present in the rustic mode.
My personal use case is to pass `-p package_name` as I'm hitting this bug way too often currently: https://github.com/rust-lang/rust/issues/84970
=> Universal argument for cargo clean command

rustic-compile.el
Fixes #372
Sample `rustic-cargo-clean`:
``` shellsession
cargo clean
rust-compilation finished at Fri Jan 28 08:51:40
```
And when we pass custom parameter:
``` shellsession
cargo clean -p package
rust-compilation finished at Fri Jan 28 08:54:06
```
=> Insert command into the compilation buffer

rustic-babel.el, rustic-cargo.el, rustic.el
This commit -> 7544d8179b5f7f59aa98d45fe4cd4a127e13bbf1 shows the `buffer-workspaces` may have some other issues.
And by the way, the `examples`  should normally run within a single crate, which I did not notice before.
=> rustic-cargo: fix cargo run --example detect crate root(#319)

rustic-cargo.el
Fixes two bugs:
- Fixes a bug when dependencies are specified as git repositories:
The `cargo outdated --depth 1` doesn't always gives the package from line number 2. For a sample project I'm having this is the output it gives:
``` shellsession
❯ cargo outdated --depth 1
Updating git repository `https://github.com/snoyberg/async-refresh-rs`
Name           Project  Compat   Latest   Kind    Platform
----           -------  ------   ------   ----    --------
anyhow         1.0.40   1.0.53   1.0.53   Normal  ---
askama         0.10.5   ---      0.11.0   Normal  ---
```
As you can see in the above case, the hardcoding of the value 2 doesn't work. The above scenario, makes cargo outdated stuff to break entirely. Infact, for me the buffer was empty and the sentinel function broke. The fix …
=> Fix bugs in rustic-cargo-outdated-mode

README.md, rustic-cargo.el
Implements two features:
- Ability to mark a specific crate to upgrade it to the latest available version
- Ability to mark all creates to upgrade to the latest available version
The README has also been updated with the relevant documentation.
=> Add ability to upgrade to latest version in rustic-outdated-mode

README.md, rustic-cargo.el, test/rustic-cargo-test.el
In order to maintain backwards compatibility, keep value empty.
Should close https://github.com/brotzeit/rustic/issues/386.
=> [cargo] add cargo-build-arguments as variable

rustic.el
If the workspace is not in a pristine state the command
prepends the stdout with warnings on stderr like
```
warning: profiles for the non root package will be ignored, specify profiles at the workspace root:
package:   blah
workspace: higher/than/blah
```
This triggered a `JSON readtable error` mentionning `119` which
is the ascii code for `w`
Ignoring stderr output allows to continue with workspace detection
even with warnings
=> Ignore stderr on cargo cmd for workspace detection

README.md, rustic-lsp.el
Provide rust-analyzer-specific initialization option `detachedFiles` when a file is not in a crate.
Closes #391
=> Add detached file support via eglot and rust-analyzer

rustic-cargo.el, test/rustic-cargo-test.el
`cargo login <TOKEN>` adds a token for https://crates.io to the local
`$CARGO_HOME/credentials` file. This is then used for `cargo`
commands that somehow interact with crates.io like `cargo publish`.
=> Add `cargo login` command

rustic-cargo.el, rustic-clippy.el, rustic-compile.el, rustic-expand.el
Two changes here:
First is to run `compilation-start-hook` as part of staring a new rustic process. This will let it more closely mirror the functionality of `compile` and work with code that uses that hook (which I often do for setting timers or watchers).
Second we change the hardcoded `g` keybinding for `rustic-recompile` to use the `remap` directive. This will ensure seamless behavior if the user has a different key for recompile (such as when using `evil-mode`).
=> remap recompile keybinding and enable `compilation-start-hook`

rustic-cargo.el
Sometimes we don't just want to run cargo check/run/test/build commands, but also cargo xrun/xcheck/xtest/xbuild, the purpose of this pr is to support customization of these commands
=> Support custom cargo check/run/build/test commands

README.md
=> add notes about automatic lsp server installation

README.md
See https://github.com/brotzeit/rustic/issues/403.
=> Add note to Installation section about rust-analyzer

rustic.el
closes #432
perhaps #433 is a more robust solution (that actually resolves for the remote path), but this stopgap solution worked for me because it would just check for cargo on the remote machine first.
=> uses `process-file` instead of `call-process` to respect remoteness of default directory

rustic-cargo.el
Hi,
I created a small PR that allows users to configure `rustic-cargo-build-arguments` when running `cargo-build` by pressing the prefix argument key `C-u`.
Can you review and consider merging it?
Thanks!
=> enable user to configure cargo-build argument when C-u is pressed

rustic-cargo.el
Hi,
I just received a failed CIL build, not sure if that was because of my commit.
But I added a small fix to make the argument of `rustic-cargo-build` optional.
Maybe it can help to resolve the failed CI.
=> make the prefix argument of cargo-build optional

rustic-cargo.el
The --locked flag can be used to force Cargo to use the packaged
Cargo.lock file if it is available.
Apart from being faster in the general cases, this is what most user
will expect to use. Also this guarantees a better reproducibile
builds.
=> change cargo install default arguments

rustic-compile.el
Setting process coding system to `utf-8-emacs-unix` for rustic processes causes issues when reading process signals on non-unix systems. An example of this is #423 . 
This PR sets the coding system of new rustic processes to the value of `default-process-coding-system` which should more reliably ensure that an appropriate coding system is used across environments.
=> Fix `rustic-format-file` hang on Windows

rustic-cargo.el
Hi, 
This is a simple PR to allow users to configure a custom `rustic-cargo-check-arguments` on when pressing `C-u`.
Can you review and consider merging it?
Thanks!
=> allow config rustic-cargo-check-arguments on C-u

rustic.el
Hi :wave: When I set `rustic-load-optional-libraries` to `nil`, I got this error on M-x `rustic-mode`:
> Symbol's value as variable is void: rustic-cargo-auto-add-missing-dependencies
I think it's because `rustic-cargo.el` is not loaded and their custom variables are not set.
This PR fixes it by adding `bound-and-true-p` check.
=> add bound check to `rustic-cargo-auto-add-missing-dependencies`

rustic-compile.el, test/rustic-compile-test.el
when called from advice around save-some-buffers, but ignore it when running rustic complile commands
close #424
=> consider buffer-save-without-query in rustic-save-some-buffers

rustic-rustfmt.el
In some situation like `org-save-all-org-buffers', one might do not want to save the rust  buffer
=> rustic-save-some-buffers-advice: respect the `pred' argument of `save-some-buffers'

rustic-compile.el
Reverts brotzeit/rustic#426
Given that #426 is now known to cause issues ( reported in [issue 423](https://github.com/brotzeit/rustic/issues/423#issuecomment-1302800867) ) without a definite understanding of how this 'fix' worked in the first place reverting it is the best course. If a true fix is found after more investigation I'll be sure to add another PR for that.
=> Revert "Fix `rustic-format-file` hang on Windows"

rustic-cargo.el
Also populate default install arguments as part of taking input from the user.
=> rustic-cargo-install: Make it work with prefix argument

rustic-cargo.el, rustic-popup.el
This also makes sure that cargo-run works in both the workflows: with and without popup/ in plain binary crate as well as examples.
Notes about changes:
- When we invoke rustic popup, the buffer-file-name becomes nil which caues it to break when running examples. So we create a new variable to tracke the source file name now.
- We optimize rustic--get-run-arguments to avoid calling to rustic-cargo-run-get-relative-example-name
- We use rustic-run-arguments as last resort. It's a good fallback to have IMO and it's default value is nil anyway.
=> Fixes edge case of running examples and plain binary

rustic-rustfmt.el
Currently, when you invoke rustic-cargo-fmt it takes a quite a bit of time because lsp-mode's rust analyzer connection disconnects and connects with each buffers that are opened in the Emacs buffer. Infact, if you visit your Messages buffer, you would be able to see the logs:
LSP::disconnected
LSP::connected with rust-analyzer
While it is a minor inconvenince for simple projects, for projects with huge number of files - it's causes a big delay.
Looking at the lsp-mode's code, this is the reason:
- When a major mode changes, the lsp-mode disconnects - https://github.com/emacs-lsp/lsp-mode/blob/a2353d0bee8465ce87f7cef1b2ee9b285cb865e2/lsp-mode.el#L4017
And the reason it is getting disconnected is, that rustic-cargo-fmt function doesn't preserve major mode when it is refreshes the text from …
=> Improve lsp-mode language server client interaction with cargo fmt

README.md, rustic-lsp.el, rustic-rustfmt.el
We do the following changes:
- Do not try to format the macro as the response from the language server (rust-analzyer) comes in the formatted fashion: https://github.com/rust-lang/rust-analyzer/pull/12014
- Avoid the extra wrapping of main to please rustfmt as it's not required anymore.
- Make rustic-analyzer-macro-expand non interactive as it's not meant to be called interactively. It's called from the lsp-mode's rust client integration.
Ultimately this fixes #473
=> Improve expand macro and LSP integration

.github/workflows/test.yml, README.md, rustic-rust-mode.el, rustic-ts-mode.el, rustic.el
=> provide alternative rustic mode that derives from rust-ts-mode

rustic-cargo.el
This MR adds support for running `cargo outdated` in workspaces. In #484 I wrote about potentially using `json` and `vtable` to fix this, but in the end I went up with just aggregating all of the crates in tabulated list mode with a new `Workspace` column showing which crate the dep came from.
I also fix some misc issues with the actual upgrading. It looks like `cargo edit` wants a `-p` flag as well?
Closes #484
=> [cargo-outdated] Add support for workspaces

README.md, rustic-babel.el, test/rustic-babel-test.el
This bug is easily reproducible when you use try something like this:
```
let x = [1,2,3,4,5,6];
println!("{x:?}");
```
And then try executing it. While you will get the result properly, you could see in the Messages buffer that that would be some errors related to compilation buffer.
And the reason is this: It tries to do rustfmt on the babel block and fails. In this fix, I just disable doing rustfmt when we have enabled automatic wrapping or when we instruct it to wrap the main function.
Another alternative fix could be do rustfmt on the wrapped main function and the remove the wrapped main function and render it again on the babel blocks. But IMO, that's going to be very fragile.
=> Fix org-babel workflow when auto wrapping main function

README.md, rustic-babel.el, rustic-cargo.el, rustic-comint.el, rustic-compile.el, rustic-doc.el, rustic-flycheck.el, rustic-lsp.el, rustic-popup.el, rustic-racer.el, rustic-rustfmt.el, rustic-spellcheck.el, rustic.el
Propagate process-environment and exec-path to any auxiliary buffer which is created, so that [envrc](https://github.com/purcell/envrc) mode works.
An example requirement for this is with [Nix development shells via direnv](https://nixos.wiki/wiki/Development_environment_with_nix-shell).  With this, the Rust compiler, rust-analyzer, et al are not on the user's default path, but only on a local path configured by direnv within the project directory.
Two different mechanisms are used to make this work.
1. Code which makes use of `get-buffer-create` or `generate-new-buffer` is wrapped in [inheritenv](https://github.com/purcell/inheritenv)
2. A macro which wraps `with-temp-buffer` is used in place of that, since inheritenv does not handle that case, adapted from …
=> Make envrc mode work

rustic-cargo.el
I found a bug when using cargo update that I introduced with my last refactor. The issue is that I was trying to check whether we had a cargo project without a workspace. In this case the goal was to append a dummy name ("---"). Unfortunately, I only checked how many crates in the workspace there where, not whether the first crate doesn't have a name (this only happens in projects without a workspace)
=> [cargo outdated] Fix bug when only one crate needs updates

rustic-cargo.el
Previously I refactored cargo-outdated so that is does not use `rustic-cargo-outdated--skip-to-packages`. However, I forgot to actually remove the function definition. This commit does that
Sorry for all of the PR's, hopefully this will be the last one in a while
=> Remove dead code in `cargo-outdated`

README.md
Also discourage users from using rls
=> Docs: Using rust-analyzer from rustup
